import Head from "next/head";
import styles from "../styles/Home.module.css";
import Start from "../components/HomeComponents/Start";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dark Puzzle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Start />
      </main>
    </div>
  );
};

export default Home;
